## Data set to be processed:

In [1]:
records = [
    {"name": "Ava", "score": 95, "hours_studied": 10},
    {"name": "Ben", "score": None, "hours_studied": 8},
    {"name": "Cara", "score": 88, "hours_studied": None},
    {"name": "", "score": 72, "hours_studied": 6},
    {"name": "Eli", "score": 105, "hours_studied": 9},
    {"name": "Finn", "score": 65, "hours_studied": 7}
]

## Step 1: Validate the records

In [4]:
def validate_records(records):
    if not isinstance(records, list):
        raise TypeError("Input must be a list")

    for record in records:
        if not isinstance(record, dict):
            raise TypeError("Each record must be a dictionary")

validate_records(records)
print("Validation passed!")

Validation passed!

## Step 2: Clean names to remove blanks

In [5]:
def clean_names(records):
    cleaned = []

    for record in records:
        if record["name"] != "":
            cleaned.append(record)

    return cleaned

In [6]:
cleaned_records = clean_names(records)
cleaned_records

[{'name': 'Ava', 'score': 95, 'hours_studied': 10},
 {'name': 'Ben', 'score': None, 'hours_studied': 8},
 {'name': 'Cara', 'score': 88, 'hours_studied': None},
 {'name': 'Eli', 'score': 105, 'hours_studied': 9},
 {'name': 'Finn', 'score': 65, 'hours_studied': 7}]

## Step 3: Fill missing scores and hours studied values

In [8]:
def fill_missing_values(records):
    scores = []
    hours = []

    # Step 1: collecting valid values
    for record in records:
        if record["score"] is not None:
            scores.append(record["score"])
        if record["hours_studied"] is not None:
            hours.append(record["hours_studied"])

    # Step 2: calculating averages
    avg_score = sum(scores) / len(scores)
    avg_hours = sum(hours) / len(hours)

    # Step 3: filling missing values
    for record in records:
        if record["score"] is None:
            record["score"] = avg_score
        if record["hours_studied"] is None:
            record["hours_studied"] = avg_hours

    return records

In [9]:
filled_records = fill_missing_values(cleaned_records)
filled_records

[{'name': 'Ava', 'score': 95, 'hours_studied': 10},
 {'name': 'Ben', 'score': 88.25, 'hours_studied': 8},
 {'name': 'Cara', 'score': 88, 'hours_studied': 8.5},
 {'name': 'Eli', 'score': 105, 'hours_studied': 9},
 {'name': 'Finn', 'score': 65, 'hours_studied': 7}]

## Step 4: Fix invalid scores

In [10]:
def cap_scores(records):
    for record in records:
        if record["score"] > 100:
            record["score"] = 100

    return records

In [11]:
capped_records = cap_scores(filled_records)
capped_records

[{'name': 'Ava', 'score': 95, 'hours_studied': 10},
 {'name': 'Ben', 'score': 88.25, 'hours_studied': 8},
 {'name': 'Cara', 'score': 88, 'hours_studied': 8.5},
 {'name': 'Eli', 'score': 100, 'hours_studied': 9},
 {'name': 'Finn', 'score': 65, 'hours_studied': 7}]

## Step 5: Convert the clean records to a Panda Dataframe

In [12]:
import pandas as pd

In [13]:
def to_dataframe(records):
    df = pd.DataFrame(records)
    return df

In [14]:
df = to_dataframe(capped_records)
df

   name   score  hours_studied
0   Ava   95.00           10.0
1   Ben   88.25            8.0
2  Cara   88.00            8.5
3   Eli  100.00            9.0
4  Finn   65.00            7.0

## Step 6: Combine all previous functions into a pipeline

In [15]:
def clean_dataset(records):
    validate_records(records)
    
    records = clean_names(records)
    records = fill_missing_values(records)
    records = cap_scores(records)
    
    df = to_dataframe(records)
    
    return df

## Step 7: Return final cleaned dataframe

In [16]:
final_df = clean_dataset(records)
final_df

   name   score  hours_studied
0   Ava   95.00           10.0
1   Ben   88.25            8.0
2  Cara   88.00            8.5
3   Eli  100.00            9.0
4  Finn   65.00            7.0